export type WorkspaceLocale = "en" | "ne";

export const personalCopy = {
  en: {
    personal: "Personal workspace",
    dashboard: "Dashboard",
    transactions: "Transactions",
    accounts: "Accounts",
    categories: "Categories",
    planning: "Planning",
    budgets: "Budgets",
    loans: "Loans & EMI",
    goals: "Goals",
    reports: "Reports",
    notifications: "Notifications",
    signOut: "Sign out",
    greeting: "Welcome back",
    privateSummary: "Your private financial workspace",
    newTransaction: "New transaction",
    totalBalance: "Available balance",
    monthlyIncome: "Income this month",
    monthlyExpense: "Expense this month",
    recentTransactions: "Recent transactions",
    noTransactions: "No transactions yet. Create your first record to start tracking.",
    addAccount: "Add account",
    accountName: "Account name",
    accountNamePlaceholder: "e.g., Laxmi Sunrise Bank, Wallet, Cash",
    accountType: "Account type",
    openingBalance: "Opening balance",
    save: "Save",
    cancel: "Cancel",
    transactionType: "Type",
    account: "Account",
    category: "Category",
    amount: "Amount",
    date: "Date",
    note: "Note",
    edit: "Edit",
    remove: "Remove",
    income: "Income",
    expense: "Expense",
    transfer: "Balance Adjustment",
    fromAccount: "From Account",
    toAccount: "To Account",
    cash: "Cash",
    bank: "Bank",
    wallet: "Digital wallet",
    card: "Credit card",
    other: "Other",
    profile: "Profile",
    language: "Language",
    english: "English",
    nepali: "नेपाली",
    noAccounts: "No accounts yet. Add an account before recording transactions.",
    transactionSaved: "Transaction saved.",
    transferSaved: "Balance adjusted successfully.",
    accountSaved: "Account saved.",
    transactionUpdated: "Transaction updated.",
    transferUpdated: "Balance adjustment updated.",
    transactionDeleted: "Transaction removed.",
    deleteConfirm: "Remove this transaction?",
    addIncome: "Add income",
    addExpense: "Add expense",
    quickActions: "Quick actions",
    getStarted: "Get started",
    addFirstAccount: "Add your first account",
    addFirstTransaction: "Record your first transaction",
    setupDescription: "Complete these steps to make your dashboard useful.",
    search: "Search by note or category",
    allTransactions: "All transactions",
    clear: "Clear",
    noResults: "No records match these filters.",
    addCategory: "Add category",
    categoryName: "Category name",
    categorySaved: "Category saved.",
    categoryDeleted: "Category removed.",
    manageCategories: "Manage income and expense categories.",

    // Finance & Planning Translations
    budgetsDescription: "Set spending limits and plan your budget accordingly.",
    addBudget: "Add budget",
    noBudgets: "No budgets created yet.",
    yourBudgets: "Your budgets",
    to: "to",
    spendingLimit: "Assigned spending limit",

    loansDescription: "Keep track of borrowed or lent money and outstanding balances.",
    addLoan: "Add loan details",
    noLoans: "No loans or EMIs added yet.",
    loanDetails: "Loan details",
    borrowedLoan: "📥 Borrowed",
    lentLoan: "📤 Lent",
    dueDateLabel: "Due date",
    outstanding: "Outstanding",
    principalAmount: "Principal",
    personName: "Person or Institution name",
    loanType: "Type",
    borrowed: "Borrowed",
    lent: "Lent",
    placeholderPerson: "e.g., Ram, NIC Asia Bank",
    amountRs: "Amount (NPR)",
    outstandingAmount: "Outstanding amount",
    rateType: "Interest Rate Type",
    simpleAnnual: "Simple Annual %",
    monthlyPerThousand: "Monthly per Rs. 1000",
    annualCompound: "Annual Compound % (Banking)",
    noInterest: "No Interest (0%)",
    interestRate: "Interest Rate",
    loanStartDate: "Loan Start Date",
    loanNote: "Purpose / Note (Optional)",
    placeholderLoanNote: "e.g., Personal use, business expansion",
    viewLoanDetails: "View Details",
    loanSummary: "Loan & Repayment Summary",
    totalBorrowed: "Total Borrowed",
    totalLent: "Total Lent",
    totalOutstanding: "Total Outstanding",
    totalAccruedInterest: "Total Accrued Interest",
    totalPayable: "Total with Interest",
    loanDuration: "Duration",
    annualCapitalization: "Annual Capitalization",
    capitalizedNote: "Unpaid interest capitalized to principal",
    ledgerStatement: "Detailed Statement & Ledger",
    close: "Close",

    goalsDescription: "Set financial goals for savings or purchases.",
    addGoal: "Add savings goal",
    noGoals: "No financial goals created yet.",
    yourGoals: "Your goals",
    savingsLabel: "Savings",
    goalName: "Goal name",
    placeholderGoal: "e.g., New laptop, emergency fund",
    targetAmount: "Target amount",
    currentSavings: "Current savings",

    reportsDescription: "Automatically generated visual summary from your transactions.",
    totalIncome: "Total Income",
    totalExpense: "Total Expense",
    savingsLoss: "Savings / Loss",
    onTrackMsg: "🎉 You are on track with your savings!",
    cutSpendingMsg: "⚠️ Try to control your expenses!",
    reportDetails: "Report details",
    reportDescription: "This report is automatically generated based on your {count} transaction records.",

    notificationsDescription: "Reminders for EMI, budgets, and important alerts.",
    noNotifications: "No new notifications yet.",
    yourNotifications: "Your notifications",
    markAsRead: "Mark as read",

    // System Messages
    dbUnavailable: "Database is currently unavailable.",
    loadError: "Failed to load data. Please check your connection.",
    networkError: "Network connection error.",
    saveAccountError: "Error occurred while saving account.",
    saveTransactionError: "Error occurred while saving transaction.",
    deleteTransactionError: "Error occurred while removing transaction.",
    saveCategoryError: "Error occurred while saving category.",
    deleteCategoryError: "Error occurred while removing category.",
    expenseBreakdown: "Expense Breakdown",
    expenseSummary: "Summary of expenses by category",
    transactionSummary: "Transaction Summary",
    monthlyIncomeExpense: "Income and expense status this month",
    totalIncomeLabel: "Total Income",
    totalExpenseLabel: "Total Expense",
    savingsLabelMonth: "Savings this month",
    moreFeatures: "More Features",
    moreMenu: "More Menu",
    manageTransactions: "View and manage all your transactions",
    adminPanel: "Admin Panel",
    userManagement: "User Management",
    actions: "Actions",
    joinedDate: "Joined Date",
    role: "Role",
    emailLabel: "Email",
    fullName: "Full Name",
    searchUsers: "Search users by name or email...",
    promoteAdmin: "Make Admin",
    demoteUser: "Make User",
    promoteSuperAdmin: "Make Super Admin",
    statusActive: "Active",
    statusInactive: "Inactive",
    userRoleUpdated: "User role updated successfully.",
    errorRoleUpdate: "Failed to update user role.",
    noUsersFound: "No users matched the criteria.",
    allRoles: "All Roles",
    auditLogs: "Audit Logs",
    actionLogged: "Action logged in system.",
    profileSettings: "Profile Settings",
    personalDetails: "Personal Details",
    securityPassword: "Security & Password",
    usernameLabel: "Username",
    profilePicture: "Profile Picture",
    updateProfileInfo: "Update Profile Info",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    changePasswordBtn: "Change Password",
    deleteAccountTitle: "Account Deletion",
    deleteAccountDesc: "Requesting account deletion will schedule your account and all associated data for permanent removal in 30 days. You can cancel this request at any time within the 30 days simply by logging back in.",
    deleteAccountBtn: "Delete Account",
    verifiedAccount: "VERIFIED ACCOUNT",
    statusLabel: "Status",
    joinedLabel: "Joined",
    userRoleLabel: "Role",
    saveSuccess: "Profile updated successfully.",
    passwordChangeSuccess: "Password changed successfully.",
    passwordChangeError: "Failed to change password. Please check your current password.",
    deleteScheduled: "Account deletion scheduled. You will be logged out.",
    deleteScheduledUndo: "Your account deletion request has been cancelled and reactivated!",
    chooseFile: "Choose Image File",
    noFileChosen: "No file chosen",
    deleteAccountRequest: "Delete Account Request",
    deleteWarningPermanent: "Warning: This action is permanent!",
    deleteBullet1: "All transaction records, account details, and financial goals data will be permanently erased.",
    deleteBullet2: "You can cancel this request and recover your account within 30 days simply by logging back in.",
    deleteBullet3: "After 30 days, your account will be permanently deleted and cannot be recovered.",
    confirmPasswordRequired: "Confirm Your Password",
    enterCurrentPassword: "Enter your current password",
    areYouSureDelete: "Are you sure you want to proceed with account deletion?",
    requestDeletionBtn: "Request Deletion",
    incorrectPassword: "Incorrect password. Please try again.",
    editUserTitle: "Edit User Credentials",
    editUsername: "New Username",
    editPassword: "New Password (leave empty to keep current)",
    updateCredentialsBtn: "Update Credentials",
    credentialsUpdated: "User credentials updated successfully.",
    credentialsUpdateError: "Failed to update user credentials.",

    // Statement View Translations (English)
    statementView: "Statement View",
    listView: "List View",
    electronicStatement: "Electronic Account Statement",
    accountHolder: "Account Holder's",
    accountNumber: "Account Number",
    currencyCode: "Currency Code",
    fromDateLabel: "From Date",
    toDateLabel: "To Date",
    openingBalanceLabel: "Opening Balance",
    closingBalanceLabel: "Closing Balance",
    accountInterestRate: "Account Interest Rate",
    accruedInterest: "Accrued Interest",
    sn: "S.N",
    transactionDate: "Transaction Date",
    description: "Description",
    withdraw: "Withdraw",
    deposit: "Deposit",
    balance: "Balance",
    printStatement: "Print Statement",
    allAccountsStatement: "Consolidated (All Accounts)",
    totalWithdraw: "Total Withdraw",
    totalDeposit: "Total Deposit",
    netChange: "Net Change",
  },
  ne: {
    personal: "व्यक्तिगत खाता",
    dashboard: "ड्यासबोर्ड",
    transactions: "कारोबार",
    accounts: "खाताहरू",
    categories: "श्रेणीहरू",
    planning: "योजना",
    budgets: "बजेट",
    loans: "ऋण / किस्ता",
    goals: "लक्ष्यहरू",
    reports: "रिपोर्ट",
    notifications: "सूचनाहरू",
    signOut: "लग आउट",
    greeting: "नमस्ते",
    privateSummary: "तपाईंको निजी वित्तीय विवरण",
    newTransaction: "नयाँ कारोबार",
    totalBalance: "कुल उपलब्ध रकम",
    monthlyIncome: "यो महिनाको आम्दानी",
    monthlyExpense: "यो महिनाको खर्च",
    recentTransactions: "हालका कारोबार",
    noTransactions: "अहिलेसम्म कारोबार थपिएको छैन। पहिलो कारोबार राखेर सुरु गर्नुहोस्।",
    addAccount: "खाता थप्नुहोस्",
    accountName: "खाताको नाम",
    accountNamePlaceholder: "जस्तै: लक्ष्मी सनराइज बैंक, वालेट, नगद",
    accountType: "खाताको प्रकार",
    openingBalance: "सुरुको रकम",
    save: "सुरक्षित गर्नुहोस्",
    cancel: "रद्द",
    transactionType: "प्रकार",
    account: "खाता",
    category: "श्रेणी",
    amount: "रकम",
    date: "मिति",
    note: "टिप्पणी",
    edit: "सम्पादन",
    remove: "हटाउनुहोस्",
    income: "आम्दानी",
    expense: "खर्च",
    transfer: "मौज्दात मिलान",
    fromAccount: "पठाउने खाता (From)",
    toAccount: "प्राप्त गर्ने खाता (To)",
    cash: "नगद",
    bank: "बैंक",
    wallet: "Digital wallet",
    card: "Credit card",
    other: "अन्य",
    profile: "प्रोफाइल",
    language: "भाषा",
    english: "English",
    nepali: "नेपाली",
    noAccounts: "अहिलेसम्म कुनै खाता छैन। कारोबार राख्नुअघि खाता थप्नुहोस्।",
    transactionSaved: "कारोबार सुरक्षित भयो।",
    transferSaved: "मौज्दात मिलान सुरक्षित भयो।",
    accountSaved: "खाता सुरक्षित भयो।",
    transactionUpdated: "कारोबार सम्पादन भयो।",
    transferUpdated: "मौज्दात मिलान सम्पादन भयो।",
    transactionDeleted: "कारोबार हटाइयो।",
    deleteConfirm: "यो कारोबार हटाउने हो?",
    addIncome: "आम्दानी थप्नुहोस्",
    addExpense: "खर्च थप्नुहोस्",
    quickActions: "छिटो काम",
    getStarted: "सुरु गर्नुहोस्",
    addFirstAccount: "पहिलो खाता थप्नुहोस्",
    addFirstTransaction: "पहिलो कारोबार राख्नुहोस्",
    setupDescription: "ड्यासबोर्ड उपयोगी बनाउन यी चरण पूरा गर्नुहोस्।",
    search: "टिप्पणी वा श्रेणी खोज्नुहोस्",
    allTransactions: "सबै कारोबार",
    clear: "खाली गर्नुहोस्",
    noResults: "यी filter अनुसार कुनै विवरण भेटिएन।",
    addCategory: "श्रेणी थप्नुहोस्",
    categoryName: "श्रेणीको नाम",
    categorySaved: "श्रेणी सुरक्षित भयो।",
    categoryDeleted: "श्रेणी हटाइयो।",
    manageCategories: "आम्दानी र खर्चका श्रेणी व्यवस्थापन गर्नुहोस्।",

    // Finance & Planning Translations (Nepali)
    budgetsDescription: "आफ्नो खर्चको सीमा बनाउनुहोस् र त्यसअनुसार योजना गर्नुहोस्।",
    addBudget: "बजेट थप्नुहोस्",
    noBudgets: "अहिलेसम्म बजेट बनाइएको छैन।",
    yourBudgets: "तपाईंका बजेट",
    to: "देखि",
    spendingLimit: "तोकिएको खर्च सीमा",

    loansDescription: "लिएको वा दिएको रकम र बाँकी हिसाब व्यवस्थित राख्नुहोस्।",
    addLoan: "ऋण थप्नुहोस्",
    noLoans: "अहिलेसम्म ऋण/किस्ता थपिएको छैन।",
    loanDetails: "ऋण/किस्ता विवरण",
    borrowedLoan: "📥 लिएको ऋण",
    lentLoan: "📤 दिएको ऋण",
    dueDateLabel: "भाका मिति",
    outstanding: "बाँकी",
    principalAmount: "मूल सावाँ",
    personName: "व्यक्ति वा संस्थाको नाम",
    loanType: "प्रकार",
    borrowed: "लिएको ऋण (Borrowed)",
    lent: "दिएको ऋण (Lent)",
    placeholderPerson: "जस्तै: राम बहादुर, एनआईसी एसिया बैंक",
    amountRs: "रकम (रु.)",
    outstandingAmount: "बाँकी रकम (रु.)",
    rateType: "ब्याजदरको प्रकार",
    simpleAnnual: "साधारण वार्षिक प्रतिशत (%)",
    monthlyPerThousand: "मासिक प्रति हजार (रु.)",
    annualCompound: "वार्षिक चक्रीय प्रतिशत (%)",
    noInterest: "ब्याज नभएको (०%)",
    interestRate: "ब्याजदर",
    loanStartDate: "ऋण सुरु मिति",
    loanNote: "उदेश्य / कैफियत (वैकल्पिक)",
    placeholderLoanNote: "जस्तै: व्यक्तिगत खर्च, व्यापार विस्तार",
    viewLoanDetails: "विस्तृत विवरण",
    loanSummary: "ऋण तथा भुक्तानी सारांश",
    totalBorrowed: "जम्मा लिएको ऋण",
    totalLent: "जम्मा दिएको ऋण",
    totalOutstanding: "कुल बाँकी रकम",
    totalAccruedInterest: "कुल पाकेको ब्याज",
    totalPayable: "ब्याज सहितको कुल रकम",
    loanDuration: "कुल अवधि",
    annualCapitalization: "वार्षिक पुँजीकरण",
    capitalizedNote: "पाकेको ब्याज सावाँमा गाभियो",
    ledgerStatement: "ऋणको विस्तृत खाता (लेजर)",
    close: "बन्द गर्नुहोस्",

    goalsDescription: "बचत वा खरिदका लागि वित्तीय लक्ष्य बनाउनुहोस्।",
    addGoal: "लक्ष्य थप्नुहोस्",
    noGoals: "अहिलेसम्म कुनै लक्ष्य बनाइएको छैन।",
    yourGoals: "तपाईंका लक्ष्यहरू",
    savingsLabel: "बचत",
    goalName: "लक्ष्यको नाम",
    placeholderGoal: "जस्तै: नयाँ ल्यापटप, आपतकालीन कोष",
    targetAmount: "लक्ष्य रकम",
    currentSavings: "हालसम्म बचत",

    reportsDescription: "तपाईंले राखेका कारोबारबाट स्वतः तयार भएको वास्तविक सारांश।",
    totalIncome: "कुल आम्दानी",
    totalExpense: "कुल खर्च",
    savingsLoss: "बचत / घाटा",
    onTrackMsg: "🎉 तपाईं बचतमा हुनुहुन्छ!",
    cutSpendingMsg: "⚠️ खर्च नियन्त्रण गर्नुहोस्!",
    reportDetails: "रिपोर्ट विवरण",
    reportDescription: "यो रिपोर्ट तपाईंले प्रविष्टि गर्नुभएको {count} वटा कारोबारहरूको विवरणका आधारमा स्वतः तयार पारिएको हो।",

    notificationsDescription: "किस्ता, बजेट र अन्य आवश्यक सम्झना यहाँ देखिन्छ।",
    noNotifications: "अहिलेसम्म नयाँ सूचना छैन।",
    yourNotifications: "तपाईंका सूचनाहरू",
    markAsRead: "पढियो",

    // System Messages (Nepali)
    dbUnavailable: "डेटाबेस उपलब्ध छैन।",
    loadError: "डेटा लोड गर्न सकिएन। डेटाबेस जडान जाँच गर्नुहोस्।",
    networkError: "नेटवर्क जडानमा समस्या आयो।",
    saveAccountError: "खाता बचत गर्ने क्रममा त्रुटि भयो।",
    saveTransactionError: "कारोबार सुरक्षित गर्ने क्रममा त्रुटि भयो।",
    deleteTransactionError: "कारोबार हटाउने क्रममा त्रुटि भयो।",
    saveCategoryError: "श्रेणी सुरक्षित गर्ने क्रममा त्रुटि भयो।",
    deleteCategoryError: "श्रेणी हटाउने क्रममा त्रुटि भयो।",
    expenseBreakdown: "खर्चको वर्गीकरण (Doughnut Chart)",
    expenseSummary: "विधाहरू अनुसार खर्चको सारांश",
    transactionSummary: "कारोबार सारांश",
    monthlyIncomeExpense: "यस महिनाको आम्दानी र खर्चको अवस्था",
    totalIncomeLabel: "कुल आम्दानी (Income)",
    totalExpenseLabel: "कुल खर्च (Expense)",
    savingsLabelMonth: "यो महिनाको बचत (Savings)",
    moreFeatures: "थप सुविधाहरू",
    moreMenu: "थप मेनु",
    manageTransactions: "तपाईंका सबै कारोबारहरूको विवरण",
    adminPanel: "एडमिन प्यानल",
    userManagement: "प्रयोगकर्ता व्यवस्थापन",
    actions: "कार्यहरू",
    joinedDate: "दर्ता मिति",
    role: "भूमिका (Role)",
    emailLabel: "इमेल",
    fullName: "पूरा नाम",
    searchUsers: "नाम वा इमेलबाट प्रयोगकर्ता खोज्नुहोस्...",
    promoteAdmin: "एडमिन बनाउनुहोस्",
    demoteUser: "साधारण प्रयोगकर्ता बनाउनुहोस्",
    promoteSuperAdmin: "सुपर एडमिन बनाउनुहोस्",
    statusActive: "सक्रिय",
    statusInactive: "निष्क्रिय",
    userRoleUpdated: "प्रयोगकर्ताको भूमिका सफलतापूर्वक अपडेट गरियो।",
    errorRoleUpdate: "भूमिका अपडेट गर्न असफल भयो।",
    noUsersFound: "कुनै पनि प्रयोगकर्ता भेटिएनन्।",
    allRoles: "सबै भूमिकाहरू",
    auditLogs: "अडिट लग (Audit Logs)",
    actionLogged: "कार्य प्रणालीमा रेकर्ड गरियो।",
    profileSettings: "प्रोफाइल सेटिङ्स",
    personalDetails: "व्यक्तिगत विवरण",
    securityPassword: "सुरक्षा र पासवर्ड",
    usernameLabel: "प्रयोगकर्ता नाम (Username)",
    profilePicture: "प्रोफाइल तस्बिर",
    updateProfileInfo: "प्रोफाइल जानकारी अपडेट गर्नुहोस्",
    currentPassword: "हालको पासवर्ड",
    newPassword: "नयाँ पासवर्ड",
    confirmNewPassword: "नयाँ पासवर्ड पुष्टि गर्नुहोस्",
    changePasswordBtn: "पासवर्ड परिवर्तन गर्नुहोस्",
    deleteAccountTitle: "खाता हटाउने (Account Deletion)",
    deleteAccountDesc: "खाता हटाउन अनुरोध गर्दा तपाईंको खाता र सम्बद्ध सबै डेटा ३० दिनमा स्थायी रूपमा हटाउनको लागि निर्धारित हुनेछ। तपाईंले ३० दिनभित्र लग इन गरेर कुनै पनि समयमा यो अनुरोध रद्द गर्न सक्नुहुन्छ।",
    deleteAccountBtn: "खाता मेटाउनुहोस्",
    verifiedAccount: "प्रमाणित खाता",
    statusLabel: "स्थिति",
    joinedLabel: "दर्ता मिति",
    userRoleLabel: "भूमिका",
    saveSuccess: "प्रोफाइल सफलतापूर्वक अपडेट गरियो।",
    passwordChangeSuccess: "पासवर्ड सफलतापूर्वक परिवर्तन भयो।",
    passwordChangeError: "पासवर्ड परिवर्तन गर्न असफल भयो। कृपया हालको पासवर्ड जाँच गर्नुहोस्।",
    deleteScheduled: "खाता हटाउने कार्य अनुसूचित गरियो। तपाईं लग आउट हुनुहुनेछ।",
    deleteScheduledUndo: "तपाईंको खाता मेटाउने अनुरोध रद्द गरिएको छ र पुन: सक्रिय गरिएको छ!",
    chooseFile: "तस्विर फाइल छान्नुहोस्",
    noFileChosen: "कुनै फाइल छानिएको छैन",
    deleteAccountRequest: "खाता मेटाउने अनुरोध",
    deleteWarningPermanent: "चेतावनी: यो कार्य स्थायी हुनेछ!",
    deleteBullet1: "सबै कारोबार विवरण, खाताहरू र वित्तीय लक्ष्यहरूको डेटा स्थायी रूपमा मेटिनेछ।",
    deleteBullet2: "तपाईंले ३० दिनभित्र लग इन गरेर कुनै पनि समयमा यो अनुरोध रद्द गर्न सक्नुहुन्छ।",
    deleteBullet3: "३० दिन पछि, तपाईंको खाता स्थायी रूपमा मेटिनेछ र पुन: प्राप्त गर्न सकिने छैन।",
    confirmPasswordRequired: "तपाईंको पासवर्ड पुष्टि गर्नुहोस्",
    enterCurrentPassword: "तपाईंको हालको पासवर्ड प्रविष्ट गर्नुहोस्",
    areYouSureDelete: "के तपाईं साँच्चिकै खाता मेटाउने प्रक्रिया अगाडि बढाउन चाहनुहुन्छ?",
    requestDeletionBtn: "मेटाउन अनुरोध गर्नुहोस्",
    incorrectPassword: "गलत पासवर्ड। कृपया पुनः प्रयास गर्नुहोस्।",
    editUserTitle: "प्रयोगकर्ता विवरण सम्पादन गर्नुहोस्",
    editUsername: "नयाँ युजरनेम",
    editPassword: "नयाँ पासवर्ड (परिवर्तन नगर्ने भए खाली छोड्नुहोस्)",
    updateCredentialsBtn: "विवरण अपडेट गर्नुहोस्",
    credentialsUpdated: "प्रयोगकर्ताको विवरण सफलतापूर्वक अपडेट गरियो।",
    credentialsUpdateError: "विवरण अपडेट गर्न असफल भयो।",

    // Statement View Translations (Nepali)
    statementView: "स्टेटमेन्ट दृश्य",
    listView: "सूची दृश्य",
    electronicStatement: "इलेक्ट्रोनिक खाता विवरण (Electronic Account Statement)",
    accountHolder: "खातावालाको नाम (Account Holder's)",
    accountNumber: "खाता नं. / नाम",
    currencyCode: "मुद्रा (Currency Code)",
    fromDateLabel: "सुरुको मिति (From Date)",
    toDateLabel: "अन्तिम मिति (To Date)",
    openingBalanceLabel: "सुरुको मौज्दात (Opening Balance)",
    closingBalanceLabel: "अन्तिम मौज्दात (Closing Balance)",
    accountInterestRate: "ब्याजदर (Interest Rate)",
    accruedInterest: "आर्जित ब्याज (Accrued Interest)",
    sn: "क्र.सं. (S.N)",
    transactionDate: "कारोबार मिति (Transaction Date)",
    description: "विवरण (Description)",
    withdraw: "खर्च (Withdraw)",
    deposit: "आम्दानी (Deposit)",
    balance: "मौज्दात (Balance)",
    printStatement: "स्टेटमेन्ट प्रिन्ट / PDF",
    allAccountsStatement: "एकीकृत (सबै खाताहरू)",
    totalWithdraw: "जम्मा खर्च",
    totalDeposit: "जम्मा आम्दानी",
    netChange: "खुद परिवर्तन",
  },
} as const;
