export type WorkspaceLocale = "en" | "ne";

export const personalCopy = {
  en: {
    personal: "Personal workspace",
    dashboard: "Dashboard",
    transactions: "Transactions",
    accounts: "Accounts",
    categories: "Categories",
    planning: "Planning",
    budgets: "Budgets",
    loans: "Loans & EMI",
    goals: "Goals",
    reports: "Reports",
    notifications: "Notifications",
    signOut: "Sign out",
    greeting: "Welcome back",
    privateSummary: "Your private financial workspace",
    newTransaction: "New transaction",
    totalBalance: "Available balance",
    monthlyIncome: "Income this month",
    monthlyExpense: "Expense this month",
    recentTransactions: "Recent transactions",
    noTransactions: "No transactions yet. Create your first record to start tracking.",
    addAccount: "Add account",
    accountName: "Account name",
    accountType: "Account type",
    openingBalance: "Opening balance",
    save: "Save",
    cancel: "Cancel",
    transactionType: "Type",
    account: "Account",
    category: "Category",
    amount: "Amount",
    date: "Date",
    note: "Note",
    edit: "Edit",
    remove: "Remove",
    income: "Income",
    expense: "Expense",
    cash: "Cash",
    bank: "Bank",
    wallet: "Digital wallet",
    card: "Credit card",
    other: "Other",
    profile: "Profile",
    language: "Language",
    english: "English",
    nepali: "नेपाली",
    noAccounts: "No accounts yet. Add an account before recording transactions.",
    transactionSaved: "Transaction saved.",
    accountSaved: "Account saved.",
    transactionUpdated: "Transaction updated.",
    transactionDeleted: "Transaction removed.",
    deleteConfirm: "Remove this transaction?",
    addIncome: "Add income",
    addExpense: "Add expense",
    quickActions: "Quick actions",
    getStarted: "Get started",
    addFirstAccount: "Add your first account",
    addFirstTransaction: "Record your first transaction",
    setupDescription: "Complete these steps to make your dashboard useful.",
    search: "Search by note or category",
    allTransactions: "All transactions",
    clear: "Clear",
    noResults: "No records match these filters.",
    addCategory: "Add category",
    categoryName: "Category name",
    categorySaved: "Category saved.",
    categoryDeleted: "Category removed.",
    manageCategories: "Manage income and expense categories.",

    // Finance & Planning Translations
    budgetsDescription: "Set spending limits and plan your budget accordingly.",
    addBudget: "Add budget",
    noBudgets: "No budgets created yet.",
    yourBudgets: "Your budgets",
    to: "to",
    spendingLimit: "Assigned spending limit",

    loansDescription: "Keep track of borrowed or lent money and outstanding balances.",
    addLoan: "Add loan details",
    noLoans: "No loans or EMIs added yet.",
    loanDetails: "Loan details",
    borrowedLoan: "📥 Borrowed",
    lentLoan: "📤 Lent",
    dueDateLabel: "Due date",
    outstanding: "Outstanding",
    principalAmount: "Principal",
    personName: "Person or Institution name",
    loanType: "Type",
    borrowed: "Borrowed",
    lent: "Lent",
    placeholderPerson: "e.g., Ram, NIC Asia Bank",
    amountRs: "Amount (NPR)",
    outstandingAmount: "Outstanding amount",

    goalsDescription: "Set financial goals for savings or purchases.",
    addGoal: "Add savings goal",
    noGoals: "No financial goals created yet.",
    yourGoals: "Your goals",
    savingsLabel: "Savings",
    goalName: "Goal name",
    placeholderGoal: "e.g., New laptop, emergency fund",
    targetAmount: "Target amount",
    currentSavings: "Current savings",

    reportsDescription: "Automatically generated visual summary from your transactions.",
    totalIncome: "Total Income",
    totalExpense: "Total Expense",
    savingsLoss: "Savings / Loss",
    onTrackMsg: "🎉 You are on track with your savings!",
    cutSpendingMsg: "⚠️ Try to control your expenses!",
    reportDetails: "Report details",
    reportDescription: "This report is automatically generated based on your {count} transaction records.",

    notificationsDescription: "Reminders for EMI, budgets, and important alerts.",
    noNotifications: "No new notifications yet.",
    yourNotifications: "Your notifications",
    markAsRead: "Mark as read",

    // System Messages
    dbUnavailable: "Database is currently unavailable.",
    loadError: "Failed to load data. Please check your connection.",
    networkError: "Network connection error.",
    saveAccountError: "Error occurred while saving account.",
    saveTransactionError: "Error occurred while saving transaction.",
    deleteTransactionError: "Error occurred while removing transaction.",
    saveCategoryError: "Error occurred while saving category.",
    deleteCategoryError: "Error occurred while removing category.",
    expenseBreakdown: "Expense Breakdown",
    expenseSummary: "Summary of expenses by category",
    transactionSummary: "Transaction Summary",
    monthlyIncomeExpense: "Income and expense status this month",
    totalIncomeLabel: "Total Income",
    totalExpenseLabel: "Total Expense",
    savingsLabelMonth: "Savings this month",
    moreFeatures: "More Features",
    moreMenu: "More Menu",
    manageTransactions: "View and manage all your transactions",
    adminPanel: "Admin Panel",
    userManagement: "User Management",
    actions: "Actions",
    joinedDate: "Joined Date",
    role: "Role",
    emailLabel: "Email",
    fullName: "Full Name",
    searchUsers: "Search users by name or email...",
    promoteAdmin: "Make Admin",
    demoteUser: "Make User",
    promoteSuperAdmin: "Make Super Admin",
    statusActive: "Active",
    statusInactive: "Inactive",
    userRoleUpdated: "User role updated successfully.",
    errorRoleUpdate: "Failed to update user role.",
    noUsersFound: "No users matched the criteria.",
    allRoles: "All Roles",
    auditLogs: "Audit Logs",
    actionLogged: "Action logged in system.",
  },
  ne: {
    personal: "व्यक्तिगत खाता",
    dashboard: "ड्यासबोर्ड",
    transactions: "कारोबार",
    accounts: "खाताहरू",
    categories: "श्रेणीहरू",
    planning: "योजना",
    budgets: "बजेट",
    loans: "ऋण / किस्ता",
    goals: "लक्ष्यहरू",
    reports: "रिपोर्ट",
    notifications: "सूचनाहरू",
    signOut: "लग आउट",
    greeting: "नमस्ते",
    privateSummary: "तपाईंको निजी वित्तीय विवरण",
    newTransaction: "नयाँ कारोबार",
    totalBalance: "कुल उपलब्ध रकम",
    monthlyIncome: "यो महिनाको आम्दानी",
    monthlyExpense: "यो महिनाको खर्च",
    recentTransactions: "हालका कारोबार",
    noTransactions: "अहिलेसम्म कारोबार थपिएको छैन। पहिलो कारोबार राखेर सुरु गर्नुहोस्।",
    addAccount: "खाता थप्नुहोस्",
    accountName: "खाताको नाम",
    accountType: "खाताको प्रकार",
    openingBalance: "सुरुको रकम",
    save: "सुरक्षित गर्नुहोस्",
    cancel: "रद्द",
    transactionType: "प्रकार",
    account: "खाता",
    category: "श्रेणी",
    amount: "रकम",
    date: "मिति",
    note: "टिप्पणी",
    edit: "सम्पादन",
    remove: "हटाउनुहोस्",
    income: "आम्दानी",
    expense: "खर्च",
    cash: "नगद",
    bank: "बैंक",
    wallet: "Digital wallet",
    card: "Credit card",
    other: "अन्य",
    profile: "प्रोफाइल",
    language: "भाषा",
    english: "English",
    nepali: "नेपाली",
    noAccounts: "अहिलेसम्म कुनै खाता छैन। कारोबार राख्नुअघि खाता थप्नुहोस्।",
    transactionSaved: "कारोबार सुरक्षित भयो।",
    accountSaved: "खाता सुरक्षित भयो।",
    transactionUpdated: "कारोबार सम्पादन भयो।",
    transactionDeleted: "कारोबार हटाइयो।",
    deleteConfirm: "यो कारोबार हटाउने हो?",
    addIncome: "आम्दानी थप्नुहोस्",
    addExpense: "खर्च थप्नुहोस्",
    quickActions: "छिटो काम",
    getStarted: "सुरु गर्नुहोस्",
    addFirstAccount: "पहिलो खाता थप्नुहोस्",
    addFirstTransaction: "पहिलो कारोबार राख्नुहोस्",
    setupDescription: "ड्यासबोर्ड उपयोगी बनाउन यी चरण पूरा गर्नुहोस्।",
    search: "टिप्पणी वा श्रेणी खोज्नुहोस्",
    allTransactions: "सबै कारोबार",
    clear: "खाली गर्नुहोस्",
    noResults: "यी filter अनुसार कुनै विवरण भेटिएन।",
    addCategory: "श्रेणी थप्नुहोस्",
    categoryName: "श्रेणीको नाम",
    categorySaved: "श्रेणी सुरक्षित भयो।",
    categoryDeleted: "श्रेणी हटाइयो।",
    manageCategories: "आम्दानी र खर्चका श्रेणी व्यवस्थापन गर्नुहोस्।",

    // Finance & Planning Translations (Nepali)
    budgetsDescription: "आफ्नो खर्चको सीमा बनाउनुहोस् र त्यसअनुसार योजना गर्नुहोस्।",
    addBudget: "बजेट थप्नुहोस्",
    noBudgets: "अहिलेसम्म बजेट बनाइएको छैन।",
    yourBudgets: "तपाईंका बजेट",
    to: "देखि",
    spendingLimit: "तोकिएको खर्च सीमा",

    loansDescription: "लिएको वा दिएको रकम र बाँकी हिसाब व्यवस्थित राख्नुहोस्।",
    addLoan: "ऋण थप्नुहोस्",
    noLoans: "अहिलेसम्म ऋण/किस्ता थपिएको छैन।",
    loanDetails: "ऋण/किस्ता विवरण",
    borrowedLoan: "📥 लिएको ऋण",
    lentLoan: "📤 दिएको ऋण",
    dueDateLabel: "भाका मिति",
    outstanding: "बाँकी",
    principalAmount: "मूल रकम",
    personName: "व्यक्ति वा संस्थाको नाम",
    loanType: "प्रकार",
    borrowed: "लिएको ऋण (Borrowed)",
    lent: "दिएको ऋण (Lent)",
    placeholderPerson: "जस्तै: राम बहादुर, एनआईसी एसिया बैंक",
    amountRs: "रकम (रु.)",
    outstandingAmount: "बाँकी रकम (रु.)",

    goalsDescription: "बचत वा खरिदका लागि वित्तीय लक्ष्य बनाउनुहोस्।",
    addGoal: "लक्ष्य थप्नुहोस्",
    noGoals: "अहिलेसम्म कुनै लक्ष्य बनाइएको छैन।",
    yourGoals: "तपाईंका लक्ष्यहरू",
    savingsLabel: "बचत",
    goalName: "लक्ष्यको नाम",
    placeholderGoal: "जस्तै: नयाँ ल्यापटप, आपतकालीन कोष",
    targetAmount: "लक्ष्य रकम",
    currentSavings: "हालसम्म बचत",

    reportsDescription: "तपाईंले राखेका कारोबारबाट स्वतः तयार भएको वास्तविक सारांश।",
    totalIncome: "कुल आम्दानी",
    totalExpense: "कुल खर्च",
    savingsLoss: "बचत / घाटा",
    onTrackMsg: "🎉 तपाईं बचतमा हुनुहुन्छ!",
    cutSpendingMsg: "⚠️ खर्च नियन्त्रण गर्नुहोस्!",
    reportDetails: "रिपोर्ट विवरण",
    reportDescription: "यो रिपोर्ट तपाईंले प्रविष्टि गर्नुभएको {count} वटा कारोबारहरूको विवरणका आधारमा स्वतः तयार पारिएको हो।",

    notificationsDescription: "किस्ता, बजेट र अन्य आवश्यक सम्झना यहाँ देखिन्छ।",
    noNotifications: "अहिलेसम्म नयाँ सूचना छैन।",
    yourNotifications: "तपाईंका सूचनाहरू",
    markAsRead: "पढियो",

    // System Messages (Nepali)
    dbUnavailable: "डेटाबेस उपलब्ध छैन।",
    loadError: "डेटा लोड गर्न सकिएन। डेटाबेस जडान जाँच गर्नुहोस्।",
    networkError: "नेटवर्क जडानमा समस्या आयो।",
    saveAccountError: "खाता बचत गर्ने क्रममा त्रुटि भयो।",
    saveTransactionError: "कारोबार सुरक्षित गर्ने क्रममा त्रुटि भयो।",
    deleteTransactionError: "कारोबार हटाउने क्रममा त्रुटि भयो।",
    saveCategoryError: "श्रेणी सुरक्षित गर्ने क्रममा त्रुटि भयो।",
    deleteCategoryError: "श्रेणी हटाउने क्रममा त्रुटि भयो।",
    expenseBreakdown: "खर्चको वर्गीकरण (Doughnut Chart)",
    expenseSummary: "विधाहरू अनुसार खर्चको सारांश",
    transactionSummary: "कारोबार सारांश",
    monthlyIncomeExpense: "यस महिनाको आम्दानी र खर्चको अवस्था",
    totalIncomeLabel: "कुल आम्दानी (Income)",
    totalExpenseLabel: "कुल खर्च (Expense)",
    savingsLabelMonth: "यो महिनाको बचत (Savings)",
    moreFeatures: "थप सुविधाहरू",
    moreMenu: "थप मेनु",
    manageTransactions: "तपाईंका सबै कारोबारहरूको विवरण",
    adminPanel: "एडमिन प्यानल",
    userManagement: "प्रयोगकर्ता व्यवस्थापन",
    actions: "कार्यहरू",
    joinedDate: "दर्ता मिति",
    role: "भूमिका (Role)",
    emailLabel: "इमेल",
    fullName: "पूरा नाम",
    searchUsers: "नाम वा इमेलबाट प्रयोगकर्ता खोज्नुहोस्...",
    promoteAdmin: "एडमिन बनाउनुहोस्",
    demoteUser: "साधारण प्रयोगकर्ता बनाउनुहोस्",
    promoteSuperAdmin: "सुपर एडमिन बनाउनुहोस्",
    statusActive: "सक्रिय",
    statusInactive: "निष्क्रिय",
    userRoleUpdated: "प्रयोगकर्ताको भूमिका सफलतापूर्वक अपडेट गरियो।",
    errorRoleUpdate: "भूमिका अपडेट गर्न असफल भयो।",
    noUsersFound: "कुनै पनि प्रयोगकर्ता भेटिएनन्।",
    allRoles: "सबै भूमिकाहरू",
    auditLogs: "अडिट लग (Audit Logs)",
    actionLogged: "कार्य प्रणालीमा रेकर्ड गरियो।",
  },
} as const;
